apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%   #How many instances created when doing new release
      maxUnavailable: 25%   #How many can be unavailable when new release
    type: RollingUpdate   #Update will be carried our selecting one at a time
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: tonytm1234/mmv2-currency-conversion-service:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-conversion-service
      restartPolicy: Always