apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%   #How many instances created when doing new release
      maxUnavailable: 25%   #How many can be unavailable when new release
    type: RollingUpdate   #Update will be carried our selecting one at a time
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: tonytm1234/mmv2-currency-conversion-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: mmv2-currency-conversion-service
        envFrom:
          - configMapRef:
              name: currency-conversion  #name of configmap
        #env:#Moved to configmap.yaml
          #- name: CURRENCY_EXCHANGE_URI
           # value: http://currency-exchange
      restartPolicy: Always
---
#service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None #if all requests need to go to same instance
  type: LoadBalancer


---
#configmap.yaml
apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default


